### PR TITLE
install to /usr/bin and generate rpm

### PR DESCRIPTION
**Pull request by vhdirk**
For installing on Fedora IoT we need rpm packages. 
Additionally, libostree only allows installation to `/usr/bin`, not `/usr/local/bin`

Needs: 
* https://github.com/eclipse-kanto/suite-connector/pull/38
* https://github.com/eclipse-kanto/file-upload/pull/43
* https://github.com/eclipse-kanto/container-management/pull/37
* https://github.com/eclipse-kanto/software-update/pull/12

### CODE REVIEW

**Comment by konstantina-gramatova** [comment]
@vhdirk  :wave: 
Thank you for your contribution and continuous interest in Kanto :star: 

To help you get acquainted with Kanto's [contributing guide](https://github.com/eclipse-kanto/kanto/blob/main/CONTRIBUTING.md), I created a couple of tickets for you that provide a little more background and [traceability](https://github.com/orgs/eclipse-kanto/projects/1/views/1) for this great new features - I hope you don't mind. It would be great if you could update the this PR's (and the linked ones) description to refer to the relevant tickets as hinted in [the guide](https://github.com/eclipse-kanto/kanto/blob/main/CONTRIBUTING.md#making-your-changes) :blush:

**Comment by konstantina-gramatova** [comment]
@vhdirk  The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).

This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances :blush: 

Please, provide your feedback as a quote reply to this message ([e.g.](https://github.com/eclipse-kanto/container-management/pull/33#issuecomment-1220400696)) that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

**Comment by vhdirk** [comment]
> @vhdirk The Eclipse Kanto project is currently restructuring its license scheme - from Eclipse Public License 2.0 only to dual licensing under Eclipse Public License 2.0 **and** Apache License 2.0 (you can read more about it [here](https://projects.eclipse.org/projects/iot.kanto/reviews/restructuring-review)).
> 
> This contribution will be merged into the project with this new licensing scheme so its important for the project and the community to have your agreement on proceeding with it given these new circumstances blush
> 
> Please, provide your feedback as a quote reply to this message ([e.g.](https://github.com/eclipse-kanto/container-management/pull/33#issuecomment-1220400696)) that you, as an author of this contribution, understand and agree with the change explained above. Thank you!

I understand and agree with the license change explained above.

**Comment by konstantina-gramatova** [comment]
@vhdirk how have you handled the installed services management in your Fedora IoT setup (enabling, start, etc.) - systemd presets by the image administrator I guess?

**Comment by vhdirk** [comment]
When creating an image, I first install the package using rpm-ostree. Then after reboot, I have an instruction that runs:
` systemctl enable suite-connector file-upload software-update container-management`

If they could be enabled automatically, that'd be awesome. But I take it that the suite-connector and the local-digital-twin are mutually exclusive?

**Comment by konstantina-gramatova** [comment]
They can be enabled with the installation of the package - it all depends on how you would like to handle the administration of your image - whether the enablement is handled by the package (can be overridden later by the administrator) or by the administrator only. 
Regarding the suite-connector and local-digital-twins - no issue to have them both enabled and even started - the **one** you configure with the desired remote connectivity endpoint, etc. will be then the only one actually handling this connection.

**Comment by vhdirk** [comment]
I don't have an immediate preference TBH. But if I had to choose, I'd go for having them enabled by default. That seems to be the most common way services are installed in, for instance, debian. But I'm fine either way, really.

**Review by konstantina-gramatova — APPROVED** [review]

**Pull request merged**
